# Module: NumPy Assignments
## Lesson: NumPy


In [1]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [15]:
arr = np.random.randint(1,21, size=(5,5))
arr


# replacing 3rd column with one

arr[:,2] = 1
arr


array([[ 4, 15,  1, 10, 18],
       [ 8, 15,  1,  7, 17],
       [17,  5,  1,  9,  5],
       [ 3, 11,  1,  8,  4],
       [ 1,  9,  1, 15,  4]], dtype=int32)

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.



In [21]:
arr = np.arange(1,17).reshape(4,4)
arr

np.fill_diagonal(arr,0)
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.



In [26]:
arr = np.arange(1,37).reshape(6,6)

print(arr)
print()

sub_arr = arr[2:6,1:4]
print(sub_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[14 15 16]
 [20 21 22]
 [26 27 28]
 [32 33 34]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.



In [29]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)
print()

border_elements = np.concatenate((arr[0,:], arr[4,:], arr[1:4, 1], arr[1:4,4]))
print(border_elements)

[[ 2 11 12  2 13]
 [ 7 13 15 10  3]
 [ 2 18 13 10  3]
 [ 3 19 14  1 18]
 [ 1  2 13 16 19]]

[ 2 11 12  2 13  1  2 13 16 19 13 18 19  3  3 18]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.



In [32]:
arr1 = np.random.randint(1,21,size=(3,4))
arr2 = np.random.randint(1,21,size=(3,4))


print(arr1)
print()
print(arr2)
print()

print("Element wise operations")
print

print(f"Addition: {arr1+arr2}")
print()
print(f"Subtraction: {arr1-arr2}")
print()
print(f"Multiplication: {arr1*arr2}")
print()
print(f"Division: {arr1/arr2}")

[[ 7  6  8  2]
 [10 17  5 10]
 [10 20 19  3]]

[[18  1 13 17]
 [12 10  1 14]
 [13 12  8 12]]

Element wise operations
Addition: [[25  7 21 19]
 [22 27  6 24]
 [23 32 27 15]]

Subtraction: [[-11   5  -5 -15]
 [ -2   7   4  -4]
 [ -3   8  11  -9]]

Multiplication: [[126   6 104  34]
 [120 170   5 140]
 [130 240 152  36]]

Division: [[0.38888889 6.         0.61538462 0.11764706]
 [0.83333333 1.7        5.         0.71428571]
 [0.76923077 1.66666667 2.375      0.25      ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.



In [34]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

sum_row = np.sum(arr,axis=1)
sum_col = np.sum(arr,axis=0)

print()
print(f"Row: {sum_row}")
print()
print(f"Col: {sum_col}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row: [10 26 42 58]

Col: [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [37]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
variance = np.var(arr)

print()
print(f"Mean: ", mean)
print(f"Median: ", median)
print(f"Standard Deviation: ", std_dev)
print(f"Variance: ", mean)



[[ 4 16 17 18  1]
 [11 19 14  7 19]
 [12  9 10 15  7]
 [ 2  5  1 15 17]
 [ 8 11 18  8  1]]

Mean:  10.6
Median:  11.0
Standard Deviation:  5.939696961966999
Variance:  10.6


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).



In [39]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
print()


mean = np.mean(arr)
std = np.std(arr)
print(f"Mean: {mean}")
print(f"Std: {std}")

print()

noramlized_arr = (arr-mean)/std
print(f"Normalized Array: {noramlized_arr}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean: 5.0
Std: 2.581988897471611

Normalized Array: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [45]:
arr = np.random.randint(1,21,size=(3,3))
print(arr)
print()

row_array = np.random.randint(1, 11, size=(3,))

print("1D array:")
print(row_array)
print()

res = arr+row_array
print("Result: ", res)


[[ 7 18 15]
 [10 13  9]
 [13 17 14]]

1D array:
[6 4 5]

Result:  [[13 22 20]
 [16 17 14]
 [19 21 19]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.



In [46]:
arr = np.random.randint(1,21,size=(4,4))
print(arr)
print()

row_array = np.random.randint(1, 21, size=(4,))

print("1D array:")
print(row_array)
print()

res = arr-row_array
print("Result: ", res)


[[20 19 10 17]
 [20  3  1 15]
 [14  4  3 10]
 [19 15  5 14]]

1D array:
[ 1 13  1  6]

Result:  [[ 19   6   9  11]
 [ 19 -10   0   9]
 [ 13  -9   2   4]
 [ 18   2   4   8]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [52]:

arr = np.random.randint(1, 11, size=(3, 3))
print(arr)
print()

det = np.linalg.det(arr)
inv = np.linalg.inv(arr)
eigen = np.linalg.eigvals(arr)


print(f"Determinate: {det}")
print(f"Inverse: {inv}")
print(f"Eigen: {eigen}")

[[9 1 6]
 [9 4 2]
 [5 2 9]]

Determinate: 205.00000000000006
Inverse: [[ 0.15609756  0.01463415 -0.10731707]
 [-0.34634146  0.24878049  0.17560976]
 [-0.0097561  -0.06341463  0.13170732]]
Eigen: [15.88897041+0.j          3.05551479+1.88834876j  3.05551479-1.88834876j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.



In [54]:
arr1 = np.random.randint(1,20,size=(2,3))
arr2 = np.random.randint(1,20,size=(3,2))


print(f"Array 1: {arr1}")
print()
print(f"Array 2: {arr2}")


res = arr1.dot(arr2)
print(f"\nResult: {res}")


Array 1: [[16 13  8]
 [ 7  3  6]]

Array 2: [[11  2]
 [ 2 12]
 [12  7]]

Result: [[298 244]
 [155  92]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).



In [55]:
arr = np.random.randint(1,20,size=(3,3))
print(arr)

reshaped_arr = arr.reshape(1,9)
print(f"\nReshaped Array: {reshaped_arr}")

reshaped_arr_1 = reshaped_arr.reshape(9,1)
print(f"\nReshaped Array 1: {reshaped_arr_1}")

[[14 17  3]
 [14 15  3]
 [13  7  3]]

Reshaped Array: [[14 17  3 14 15  3 13  7  3]]

Reshaped Array 1: [[14]
 [17]
 [ 3]
 [14]
 [15]
 [ 3]
 [13]
 [ 7]
 [ 3]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).



In [56]:
arr = np.random.randint(1,101,size=(5,5))
print(arr)

reshaped_arr = arr.reshape(1,25)
print(f"\nReshaped Array: {reshaped_arr}")

reshaped_arr_1 = reshaped_arr.reshape(5,5)
print(f"\nReshaped Array 1: {reshaped_arr_1}")

[[93 61 74 62 70]
 [90 21 31 60 12]
 [66 52 38 11 93]
 [69 34 52 52 99]
 [67 20 75 87 54]]

Reshaped Array: [[93 61 74 62 70 90 21 31 60 12 66 52 38 11 93 69 34 52 52 99 67 20 75 87
  54]]

Reshaped Array 1: [[93 61 74 62 70]
 [90 21 31 60 12]
 [66 52 38 11 93]
 [69 34 52 52 99]
 [67 20 75 87 54]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [59]:
arr = np.random.randint(1,101,size=(5,5))
print(arr)



corners = arr[[0,0,4,4],[0,4,0,4]] 
print(f"Corners: {corners}")

[[74 80 24  4 39]
 [45 74 84 74 82]
 [73 98 72  2 30]
 [83 47 46 34 13]
 [15 68 84 37 72]]
Corners: [74 39 15 72]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.



In [63]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)

arr[arr>10] = 10
print()
print(arr)

[[ 4 20  5 13 15]
 [ 9 17 11  2  1]
 [17 12  4  9  7]
 [ 9  2 10  1  5]
 [19  3 18 20  8]]

[[ 4 10  5 10 10]
 [ 9 10 10  2  1]
 [10 10  4  9  7]
 [ 9  2 10  1  5]
 [10  3 10 10  8]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [67]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
arr = np.array([('Ali', 22, 75.7), ('Sameed', 21, 56.7), ('Arbani', 26, 56.7)], dtype=data_type)
print(arr)

sorted_by_age = np.sort(arr,order='age')
print()
print(sorted_by_age)

[('Ali', 22, 75.7) ('Sameed', 21, 56.7) ('Arbani', 26, 56.7)]

[('Sameed', 21, 56.7) ('Ali', 22, 75.7) ('Arbani', 26, 56.7)]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [68]:
import numpy.ma as ma

arr = np.random.randint(1,21,size=(4,4))
masked_arr = ma.masked_greater(arr,10)

print(arr)
print()
print(f"Maksed: {masked_arr}")

unmsked_sum = masked_arr.sum()
print()
print(unmsked_sum)

[[19 11 19  9]
 [15 11 11  1]
 [ 4 18  3  8]
 [14  9 13  8]]

Maksed: [[-- -- -- 9]
 [-- -- -- 1]
 [4 -- 3 8]
 [-- 9 -- 8]]

42


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:

array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)


mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[19 19 15]
 [19 19 13]
 [12 17  6]]
Masked array:
[[-- 19 15]
 [19 -- 13]
 [12 17 --]]
Modified masked array:
[[15 19 15]
 [19 15 13]
 [12 17 15]]


I need practice in masked thing